Repository jpetazzo/container.training, pull requests merged in 2018-06, with the labels that each got.

#273 Add a few slides about resource limits
  slides/intro-fullday.yml
  slides/intro-selfpaced.yml
  slides/intro/Resource_Limits.md
Labels: containers

#269 Show how to access internal services with kubectl proxy
  slides/kube-fullday.yml
  slides/kube-halfday.yml
  slides/kube-selfpaced.yml
  slides/kube/kubectlproxy.md
Labels: k8s

#271 Replace index.html with a generator
  .gitignore
  slides/build.sh
  slides/index.css
  slides/index.html
  slides/index.py
  slides/index.yaml
  slides/requirements.txt
Labels: tools

#277 Clarifying rollout failure via dashboard
  slides/kube/rollout.md
Labels: k8s
